# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/wearit_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456789iagofdz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=wearit_secreto_muy_largo_para_produccion_2024
jwt.expiration=86400000

# Imagenes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.imagen.base-url=http://localhost:8080

openweather.api.key=3efe0a4422fa748918aaea27f7e1626c
removebg.api.key=NCzAB9tYmaw2Z4KT4LozW9h6

spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false